spring:
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: false
        service-id: config-server
  config:
    import: configserver:http://localhost:8888
  application:
    name: image-service
  profiles:
    active: dev
