spring:
  application:
    name: image-service
server:
  port: 0
image:
  path: /Programming/Java/StreamingService/Backend/image-service/images
  default: /Programming/Java/StreamingService/Backend/image-service/images/default_audio.png
logging:
  level:
    '[org.springframework.web]': debug