spring:
  application:
    name: image-service
server:
  port: 0
image:
  path: /home/hhezi/Programming/JavaProjects/StreamingService/Backend/image-service/images
  default: /home/hhezi/Programming/JavaProjects/StreamingService/Backend/image-service/images/default_image.png
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
logging:
  level:
    '[org.springframework.web]': debug