spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/UserDB
    password: postgres
    username: postgres
server:
  port: 0
logging:
  level:
    '[org.springframework.web]': debug