spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/UserDB
    password: postgres
    username: postgres
server:
  port: 0
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
logging:
  level:
    '[org.springframework.web]': debug