networks:
  backend-network:
    name: backend-network
  album-network:
    name: album-network
  user-network:
    name: user-network
  auth-network:
    name: auth-network
  author-network:
   name: author-network    
  kafka-network:
   name: kafka-network
  track-network: 
   name: track-network
  playlist-network:
   name: playlist-network
  favorite-network:
   name: favorite-network
volumes:
  album-db-volume:
  user-db-volume:
  auth-db-volume:
  author-db-volume:
  track-db-volume:
  playlist-db-volume:
  favorite-db-volume:

services:
  eureka-server: 
    build: ./Backend/eureka-server/
    container_name: eureka-server
    ports:
      - 8761:8761
    networks:
      - backend-network
    healthcheck:
      test: "curl http://localhost:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      retries: 5
      start_period: 25s
      timeout: 10s

  config-server:
    build: ./Backend/config-server/
    container_name: config-server
    ports:
      - 8888:8888
    networks: 
      - backend-network 
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    depends_on: 
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: "curl http://localhost:8888/actuator/health | grep UP || exit 1"
      interval: 20s
      retries: 5
      start_period: 25s
      timeout: 20s
 
  api-gateway:
    build: ./Backend/api-gateway/
    container_name: api-gateway
    restart: always
    ports:
      - 8080:8080
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - backend-network

  album-db:
    image: postgres
    container_name: album-db
    volumes: 
    - album-db-volume:/var/lib/postgresql/data
    - ./Backend/album-service/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=AlbumDB 
      - PGUSER=postgres
    networks:
      - album-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "AlbumDB"]
      interval: 30s
      timeout: 60s

  album-service:
    build: ./Backend/album-service/
    container_name: album-service
    restart: always
    environment:
      - server.ports=8085
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.r2dbc.url=r2dbc:postgresql://album-db:5432/AlbumDB
      - spring.r2dbc.username=postgres
      - spring.r2dbc.password=postgres
      - logging.level.org.springframework.r2dbc=TRACE
      - logging.level.io.r2dbc.spi=TRACE
      - spring.kafka.bootstrap-servers=kafka:9092
    networks:
      - backend-network
      - album-network
      - kafka-network
    ports: 
      - 8085:8085
    depends_on:
      eureka-server:
        condition: service_healthy 
      album-db:
        condition: service_healthy
      kafka:
        condition: service_started  
      config-server:
        condition: service_healthy
  
  audio-service:
    build: ./Backend/audio-service/
    container_name: audio-service
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.kafka.bootstrap-servers=kafka:9092
    volumes:
      - ~/app/audio/:/audio
    networks:
      - backend-network
      - kafka-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      kafka:
        condition: service_started
  
  image-service:
    build: ./Backend/image-service
    container_name: image-service
    restart: always
    environment:
      - spring.config.import=configserver:http://config-server:8888
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.kafka.bootstrap-servers=kafka:9092
    volumes:
      - ~/app/images/:/images
    networks:
      - backend-network
      - kafka-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy  
      kafka:
        condition: service_started

  user-db:
    image: postgres
    container_name: user-db
    volumes: 
    - user-db-volume:/var/lib/postgresql/data
    - ./Backend/user-service/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=UserDB
      - PGUSER=postgres
    networks:
      - user-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "UserDB"]
      interval: 30s
      timeout: 60s  

  user-service:
    build: ./Backend/user-service
    container_name: user-service
    restart: always
    environment:
      - server.port=8084
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.r2dbc.url=r2dbc:postgresql://user-db:5432/UserDB
      - spring.r2dbc.username=postgres
      - spring.r2dbc.password=postgres
      - logging.level.org.springframework.r2dbc=TRACE
      - logging.level.io.r2dbc.spi=TRACE
    depends_on:
      eureka-server:
        condition: service_healthy
      user-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    ports:
      - 8084:8084
    networks:
      - backend-network
      - user-network
      
  auth-db:
    image: postgres
    container_name: auth-db
    volumes: 
    - auth-db-volume:/var/lib/postgresql/data
    - ./Backend/auth-service/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=AuthDB
      - PGUSER=postgres
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "AuthDB"]
      interval: 30s
      timeout: 60s

  auth-service:
    build: ./Backend/auth-service
    container_name: auth-service
    restart: always
    environment:
      - server.port=8083
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.r2dbc.url=r2dbc:postgresql://auth-db:5432/AuthDB
      - spring.r2dbc.username=postgres
      - spring.r2dbc.password=postgres
      - logging.level.org.springframework.r2dbc=TRACE
      - logging.level.io.r2dbc.spi=TRACE
    depends_on:
      auth-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy  
    ports:
      - 8083:8083
    networks:
      - backend-network
      - auth-network

  author-db:
    image: postgres
    container_name: author-db
    volumes: 
    - author-db-volume:/var/lib/postgresql/data
    - ./Backend/author-service/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=AuthorDB
      - PGUSER=postgres
    networks:
      - author-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "AuthorDB"]
      interval: 30s
      timeout: 60s

  author-service:
    build: ./Backend/author-service
    container_name: author-service
    restart: always
    environment:
      - server.port=8082
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.r2dbc.url=r2dbc:postgresql://author-db:5432/AuthorDB
      - spring.r2dbc.username=postgres
      - spring.r2dbc.password=postgres
      - spring.kafka.bootstrap-servers=kafka:9092
      - logging.level.org.springframework.r2dbc=TRACE
      - logging.level.io.r2dbc.spi=TRACE
    networks:
      - author-network
      - backend-network
      - kafka-network
    ports: 
      - 8082:8082
    depends_on:
      eureka-server:
        condition: service_healthy
      author-db:
        condition: service_healthy
      kafka:
        condition: service_started
      config-server:
        condition: service_healthy
    
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
 
  
  track-db:
    image: postgres
    container_name: track-db
    volumes: 
    - track-db-volume:/var/lib/postgresql/data
    - ./Backend/track-service/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=TrackDB
      - PGUSER=postgres
    networks:
      - track-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "TrackDB"]
      interval: 30s
      timeout: 60s
  
  track-service:
    build: ./Backend/track-service
    container_name: track-service
    restart: always
    ports:
      - 8081:8081
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - server.port=8081
      - spring.r2dbc.url=r2dbc:postgresql://track-db:5432/TrackDB
      - spring.r2dbc.username=postgres
      - spring.r2dbc.password=postgres
      - spring.kafka.bootstrap-servers=kafka:9092
      - logging.level.org.springframework.r2dbc=TRACE
      - logging.level.io.r2dbc.spi=TRACE
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_started
      track-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - backend-network
      - track-network
      - kafka-network

  playlist-db:
    image: postgres
    container_name: playlist_db
    volumes: 
    - playlist-db-volume:/var/lib/postgresql/data
    - ./Backend/playlist-service/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=PlaylistDB
      - PGUSER=postgres
    networks:
      - playlist-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "PlaylistDB"]
      interval: 30s
      timeout: 60s

  playlist-service:
    build: ./Backend/playlist-service
    container_name: playlist-service
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.r2dbc.url=r2dbc:postgresql://playlist-db:5432/PlaylistDB
      - spring.r2dbc.username=postgres
      - spring.r2dbc.password=postgres
      - spring.kafka.bootstrap-servers=kafka:9092
      - logging.level.org.springframework.r2dbc=TRACE
      - logging.level.io.r2dbc.spi=TRACE
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_started
      playlist-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - backend-network
      - playlist-network
      - kafka-network

  favorite-db:
    image: postgres
    container_name: favorite_db
    volumes: 
    - favorite-db-volume:/var/lib/postgresql/data
    - ./Backend/playlist-service/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=FavoriteDB
      - PGUSER=postgres
    networks:
      - favorite-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "FavoriteDB"]
      interval: 30s
      timeout: 60s
  
  favorite-service:
    build: ./Backend/favorite-service
    container_name: favorite-service
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.r2dbc.url=r2dbc:postgresql://favorite-db:5432/FavoriteDB
      - spring.r2dbc.username=postgres
      - spring.r2dbc.password=postgres
      - spring.kafka.bootstrap-servers=kafka:9092    
      - logging.level.org.springframework.r2dbc=TRACE
      - logging.level.io.r2dbc.spi=TRACE
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_started
      favorite-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - backend-network 
      - favorite-network
      - kafka-network