spring:
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
  config:
    import: "configserver:"
  application:
    name: favorite-service
  profiles:
    active: local
