spring:
  application:
    name: favorite-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/FavoriteDB
    password: postgres
    username: postgres
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.app.kafka.message"
        spring.json.default.value.type: com.app.kafka.message.TrackDeletionMessage
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
