spring:
  application:
    name: album-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/AlbumDB
    username: postgres
    password: postgres
server:
  port: 0
logging:
  level:
    '[org.springframework.web]': debug
file.temp: \Programming\Java\StreamingService\Backend\album-service\temp
file.max-size: 1_048_576 #1MB