spring:
  application:
    name: album-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/AlbumDB
    username: postgres
    password: postgres
server:
  port: 0
logging:
  level:
    '[org.springframework.web]': debug
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
file.temp: /home/hhezi/Programming/JavaProjects/StreamingService/Backend/album-service/temp
file.max-size: 1_048_576 #1MB