spring:
  application:
    name: auth-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/AuthDB
    username: postgres
    password: postgres
server:
  port: 0
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
token:
  secret: 9649CDE69385C16B568704B2B7A0DA4970C68D8E6FAE19A2A23472DE3AE8ED2F
