spring:
  application:
    name: track-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/TrackDB
    password: postgres
    username: postgres
  codec:
    max-in-memory-size:
      36MB
server:
  port: 0
logging:
  level:
    '[org.springframework.web]': debug
file.temp: \Programming\Java\StreamingService\Backend\track-service\temp