spring:
  application:
    name: AudioService
  datasource:
    url: jdbc:postgresql://localhost:5432/AudioService
    password: guest
    username: guest
  jpa:
    open-in-view: false
server:
  error:
    include-stacktrace: never 
  port: 0
audio.path: /Programming/Java/StreamingService/Backend/AudioService/audio
logging:
  level:
    '[org.springframework.web]': debug