spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Users
    password: postgres
    username: postgres
server:
  port: 0
logging:
  level:
    '[org.springframework.web]': debug