spring:
  application:
    name: author-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/AuthorDB
    username: postgres
    password: postgres
server:
  port: 0
logging:
  level:
    '[org.springframework.web]': debug
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
file.temp: /Programming/Java/StreamingService/Backend/author-service/temp
file.max-size: 1_048_576 #1MB