spring:
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
  config:
    import: "optional:configserver:"
  application:
    name: author-service
  profiles:
    active: local
