spring:
  application:
    name: author-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/AuthorDB
    username: postgres
    password: postgres
server:
  port: 0
logging:
  level:
    '[org.springframework.web]': debug
file.temp: \Programming\Java\StreamingService\Backend\author-service\temp