spring:
  application:
    name: playlist-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/PlaylistDB
    username: postgres
    password: postgres
server:
  port: 0
logging:
  level:
    '[org.springframework.web]': debug