spring:
  application:
    name: playlist-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/PlaylistDB
    password: postgres
    username: postgres
server:
  port: 0
logging:
  level:
    '[org.springframework.web]': debug
file.temp: \Programming\Java\StreamingService\Backend\playlist-service\temp