spring:
  application:
    name: audio-service
server:
  port: 0
audio.path: /Programming/Java/StreamingService/Backend/AudioService/audio
logging:
  level:
    '[org.springframework.web]': debug