spring:
  application:
    name: audio-service
  servlet:
    multipart:
      max-file-size: 36MB
      max-request-size: 36MB
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.app.kafka.message"
        spring.json.default.value.type: com.app.kafka.message.TrackDeletionMessage
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
server:
  port: 0
audio.path: /Programming/Java/SpringBootMusicApp/Backend/audio-service/audio
logging:
  level:
    org.springframework.kafka: DEBUG
chunk.max-size: 1_048_576 #1MB