spring:
  application:
    name: audio-service
server:
  port: 0
audio.path: /Programming/Java/StreamingService/Backend/audio-service/audio
logging:
  level:
    '[org.springframework.web]': debug