spring:
  application:
    name: audio-service
  servlet:
    multipart:
      max-file-size: 36MB
      max-request-size: 36MB
server:
  port: 0
audio.path: /Programming/Java/StreamingService/Backend/audio-service/audio
logging:
  level:
    '[org.springframework.web]': debug